name: Tests

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  # pytest colors: https://github.com/pytest-dev/pytest/issues/7443
  FORCE_COLOR: "1"

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v2

      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # preserve pip cache to speed up installation
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade . -r dev-requirements.txt
          pip freeze

      - name: Run tests
        run: |
          pytest -v --cov=firstuseauthenticator

      # GitHub action reference: https://github.com/codecov/codecov-action
      - uses: codecov/codecov-action@v4
